//! Autogenerated weights for pallet_identity
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-10-26, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("altair-dev"), DB CACHE: 1024

// Executed Command:
// target/release/centrifuge-chain
// benchmark
// pallet
// --chain=altair-dev
// --steps=50
// --repeat=20
// --pallet=pallet_identity
// --extrinsic=*
// --execution=wasm
// --wasm-execution=compiled
// --heap-pages=4096
// --output=/tmp/runtime/altair/src/weights/pallet_identity.rs
// --template=./scripts/runtime-weight-template.hbs

#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{
	traits::Get,
	weights::{constants::RocksDbWeight, Weight},
};
use pallet_identity::weights::WeightInfo;
use sp_std::marker::PhantomData;

/// Weights for pallet_identity using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	fn add_registrar(r: u32) -> Weight {
		Weight::from_ref_time(15_285_000) // Standard Error: 3_000
			.saturating_add(Weight::from_ref_time(105_000).saturating_mul(r as u64))
			.saturating_add(T::DbWeight::get().reads(1 as u64))
			.saturating_add(T::DbWeight::get().writes(1 as u64))
	}

	fn set_identity(r: u32, x: u32) -> Weight {
		Weight::from_ref_time(28_451_000) // Standard Error: 7_000
			.saturating_add(Weight::from_ref_time(84_000).saturating_mul(r as u64)) // Standard Error: 1_000
			.saturating_add(Weight::from_ref_time(313_000).saturating_mul(x as u64))
			.saturating_add(T::DbWeight::get().reads(1 as u64))
			.saturating_add(T::DbWeight::get().writes(1 as u64))
	}

	fn set_subs_new(s: u32) -> Weight {
		Weight::from_ref_time(23_680_000) // Standard Error: 3_000
			.saturating_add(Weight::from_ref_time(2_471_000).saturating_mul(s as u64))
			.saturating_add(T::DbWeight::get().reads(2 as u64))
			.saturating_add(T::DbWeight::get().reads((1 as u64).saturating_mul(s as u64)))
			.saturating_add(T::DbWeight::get().writes(1 as u64))
			.saturating_add(T::DbWeight::get().writes((1 as u64).saturating_mul(s as u64)))
	}

	fn set_subs_old(p: u32) -> Weight {
		Weight::from_ref_time(23_560_000) // Standard Error: 1_000
			.saturating_add(Weight::from_ref_time(1_074_000).saturating_mul(p as u64))
			.saturating_add(T::DbWeight::get().reads(2 as u64))
			.saturating_add(T::DbWeight::get().writes(1 as u64))
			.saturating_add(T::DbWeight::get().writes((1 as u64).saturating_mul(p as u64)))
	}

	fn clear_identity(r: u32, s: u32, x: u32) -> Weight {
		Weight::from_ref_time(26_986_000) // Standard Error: 14_000
			.saturating_add(Weight::from_ref_time(185_000).saturating_mul(r as u64)) // Standard Error: 2_000
			.saturating_add(Weight::from_ref_time(1_077_000).saturating_mul(s as u64)) // Standard Error: 2_000
			.saturating_add(Weight::from_ref_time(168_000).saturating_mul(x as u64))
			.saturating_add(T::DbWeight::get().reads(2 as u64))
			.saturating_add(T::DbWeight::get().writes(2 as u64))
			.saturating_add(T::DbWeight::get().writes((1 as u64).saturating_mul(s as u64)))
	}

	fn request_judgement(r: u32, x: u32) -> Weight {
		Weight::from_ref_time(29_995_000) // Standard Error: 5_000
			.saturating_add(Weight::from_ref_time(82_000).saturating_mul(r as u64)) // Standard Error: 0
			.saturating_add(Weight::from_ref_time(323_000).saturating_mul(x as u64))
			.saturating_add(T::DbWeight::get().reads(2 as u64))
			.saturating_add(T::DbWeight::get().writes(1 as u64))
	}

	fn cancel_request(r: u32, x: u32) -> Weight {
		Weight::from_ref_time(28_093_000) // Standard Error: 4_000
			.saturating_add(Weight::from_ref_time(47_000).saturating_mul(r as u64)) // Standard Error: 0
			.saturating_add(Weight::from_ref_time(316_000).saturating_mul(x as u64))
			.saturating_add(T::DbWeight::get().reads(1 as u64))
			.saturating_add(T::DbWeight::get().writes(1 as u64))
	}

	fn set_fee(r: u32) -> Weight {
		Weight::from_ref_time(8_280_000) // Standard Error: 3_000
			.saturating_add(Weight::from_ref_time(57_000).saturating_mul(r as u64))
			.saturating_add(T::DbWeight::get().reads(1 as u64))
			.saturating_add(T::DbWeight::get().writes(1 as u64))
	}

	fn set_account_id(r: u32) -> Weight {
		Weight::from_ref_time(8_240_000) // Standard Error: 3_000
			.saturating_add(Weight::from_ref_time(66_000).saturating_mul(r as u64))
			.saturating_add(T::DbWeight::get().reads(1 as u64))
			.saturating_add(T::DbWeight::get().writes(1 as u64))
	}

	fn set_fields(r: u32) -> Weight {
		Weight::from_ref_time(8_156_000) // Standard Error: 3_000
			.saturating_add(Weight::from_ref_time(69_000).saturating_mul(r as u64))
			.saturating_add(T::DbWeight::get().reads(1 as u64))
			.saturating_add(T::DbWeight::get().writes(1 as u64))
	}

	fn provide_judgement(r: u32, x: u32) -> Weight {
		Weight::from_ref_time(20_435_000) // Standard Error: 3_000
			.saturating_add(Weight::from_ref_time(29_000).saturating_mul(r as u64)) // Standard Error: 0
			.saturating_add(Weight::from_ref_time(313_000).saturating_mul(x as u64))
			.saturating_add(T::DbWeight::get().reads(2 as u64))
			.saturating_add(T::DbWeight::get().writes(1 as u64))
	}

	fn kill_identity(r: u32, s: u32, x: u32) -> Weight {
		Weight::from_ref_time(40_768_000) // Standard Error: 7_000
			.saturating_add(Weight::from_ref_time(101_000).saturating_mul(r as u64)) // Standard Error: 1_000
			.saturating_add(Weight::from_ref_time(1_077_000).saturating_mul(s as u64)) // Standard Error: 1_000
			.saturating_add(Weight::from_ref_time(5_000).saturating_mul(x as u64))
			.saturating_add(T::DbWeight::get().reads(4 as u64))
			.saturating_add(T::DbWeight::get().writes(4 as u64))
			.saturating_add(T::DbWeight::get().writes((1 as u64).saturating_mul(s as u64)))
	}

	fn add_sub(s: u32) -> Weight {
		Weight::from_ref_time(31_958_000) // Standard Error: 0
			.saturating_add(Weight::from_ref_time(43_000).saturating_mul(s as u64))
			.saturating_add(T::DbWeight::get().reads(3 as u64))
			.saturating_add(T::DbWeight::get().writes(2 as u64))
	}

	fn rename_sub(s: u32) -> Weight {
		Weight::from_ref_time(12_473_000) // Standard Error: 0
			.saturating_add(Weight::from_ref_time(11_000).saturating_mul(s as u64))
			.saturating_add(T::DbWeight::get().reads(2 as u64))
			.saturating_add(T::DbWeight::get().writes(1 as u64))
	}

	fn remove_sub(s: u32) -> Weight {
		Weight::from_ref_time(32_999_000) // Standard Error: 0
			.saturating_add(Weight::from_ref_time(38_000).saturating_mul(s as u64))
			.saturating_add(T::DbWeight::get().reads(3 as u64))
			.saturating_add(T::DbWeight::get().writes(2 as u64))
	}

	fn quit_sub(s: u32) -> Weight {
		Weight::from_ref_time(23_514_000) // Standard Error: 1_000
			.saturating_add(Weight::from_ref_time(39_000).saturating_mul(s as u64))
			.saturating_add(T::DbWeight::get().reads(2 as u64))
			.saturating_add(T::DbWeight::get().writes(2 as u64))
	}
}
