// Copyright 2021 Centrifuge Foundation (centrifuge.io).
//
// This file is part of the Centrifuge chain project.
// Centrifuge is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version (see http://www.gnu.org/licenses).
// Centrifuge is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.

// NOTE: Technically most code will be dead as it is only used in tests.
//       Therefore we are setting this here.qq
#![allow(dead_code)]

mod utils;

#[cfg(test)]
mod tests;

/// Liquidity-Pool solidity artifacts generated by build-script.
/// All needed contracts can be loaded from here
const LP_SOL_SOURCES: &str = env!("LP_SOL_SOURCES", "Build script failed to populate environment variable LP_SOL_SOURCES pointing to solidity source files.");

/// Axelar gateway solidity artifacts generated by build-script.
/// All needed contracts can be loaded from here
const AXELAR_SOL_SOURCES: &str = env!("AXELAR_SOL_SOURCES", "Build script failed to populate environment variable AXELAR_SOL_SOURCES pointing to solidity source files.");
