//! Autogenerated weights for pallet_fees
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 3.0.0
//! DATE: 2021-06-07, STEPS: `[50, ]`, REPEAT: 100, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("charcoal-local"), DB CACHE: 128

// Executed Command:
// target/release/centrifuge-chain
// benchmark
// --chain=charcoal-local
// --steps=50
// --repeat=100
// --pallet=pallet_fees
// --extrinsic=*
// --execution=wasm
// --wasm-execution=compiled
// --heap-pages=4096
// --output=./pallets/fees/src/weights.rs
// --template=./scripts/frame-weight-template.hbs

#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{
	traits::Get,
	weights::{constants::RocksDbWeight, Weight},
};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_fees.
pub trait WeightInfo {
	fn migrate_system_account(num_accounts: u64) -> Weight;
	fn migrate_balances_issuance() -> Weight;
	fn migrate_vesting_vesting(num_vestings: u64) -> Weight;
}

// For backwards compatibility and tests
impl WeightInfo for () {
	fn migrate_system_account(num_accounts: u64) -> Weight {
		10_0000
	}

	fn migrate_balances_issuance() -> Weight {
		10_0000
	}

	fn migrate_vesting_vesting(num_vestings: u64) -> Weight {
		10_000
	}
}
