//! Autogenerated weights for pallet_vesting
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-09-02, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("centrifuge-dev"), DB CACHE: 1024

// Executed Command:
// target/release/centrifuge-chain
// benchmark
// pallet
// --chain=centrifuge-dev
// --steps=50
// --repeat=20
// --pallet=pallet_vesting
// --extrinsic=*
// --execution=wasm
// --wasm-execution=compiled
// --heap-pages=4096
// --output=/tmp/runtime/centrifuge/src/weights/pallet_vesting.rs
// --template=./scripts/runtime-weight-template.hbs

#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{
	traits::Get,
	weights::{constants::RocksDbWeight, Weight},
};
use sp_std::marker::PhantomData;

/// Weights for pallet_vesting using the Substrate node and recommended hardware.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_vesting::WeightInfo for WeightInfo<T> {
	fn vest_locked(l: u32, s: u32) -> Weight {
		Weight::from_ref_time(67_042_000) // Standard Error: 8_000
			.saturating_add(Weight::from_ref_time(198_000).saturating_mul(l as u64)) // Standard Error: 410_000
			.saturating_add(Weight::from_ref_time(1_478_000).saturating_mul(s as u64))
			.saturating_add(T::DbWeight::get().reads(2 as u64))
			.saturating_add(T::DbWeight::get().writes(2 as u64))
	}

	fn vest_unlocked(l: u32, s: u32) -> Weight {
		Weight::from_ref_time(70_214_000) // Standard Error: 6_000
			.saturating_add(Weight::from_ref_time(157_000).saturating_mul(l as u64)) // Standard Error: 337_000
			.saturating_add(Weight::from_ref_time(341_000).saturating_mul(s as u64))
			.saturating_add(T::DbWeight::get().reads(2 as u64))
			.saturating_add(T::DbWeight::get().writes(2 as u64))
	}

	fn vest_other_locked(l: u32, s: u32) -> Weight {
		Weight::from_ref_time(67_999_000) // Standard Error: 6_000
			.saturating_add(Weight::from_ref_time(194_000).saturating_mul(l as u64)) // Standard Error: 338_000
			.saturating_add(Weight::from_ref_time(1_108_000).saturating_mul(s as u64))
			.saturating_add(T::DbWeight::get().reads(3 as u64))
			.saturating_add(T::DbWeight::get().writes(3 as u64))
	}

	fn vest_other_unlocked(l: u32, s: u32) -> Weight {
		Weight::from_ref_time(68_000_000) // Standard Error: 6_000
			.saturating_add(Weight::from_ref_time(179_000).saturating_mul(l as u64)) // Standard Error: 316_000
			.saturating_add(Weight::from_ref_time(913_000).saturating_mul(s as u64))
			.saturating_add(T::DbWeight::get().reads(3 as u64))
			.saturating_add(T::DbWeight::get().writes(3 as u64))
	}

	fn vested_transfer(l: u32, _s: u32) -> Weight {
		Weight::from_ref_time(117_867_000) // Standard Error: 11_000
			.saturating_add(Weight::from_ref_time(192_000).saturating_mul(l as u64))
			.saturating_add(T::DbWeight::get().reads(3 as u64))
			.saturating_add(T::DbWeight::get().writes(3 as u64))
	}

	fn force_vested_transfer(l: u32, _s: u32) -> Weight {
		Weight::from_ref_time(118_184_000) // Standard Error: 9_000
			.saturating_add(Weight::from_ref_time(190_000).saturating_mul(l as u64))
			.saturating_add(T::DbWeight::get().reads(4 as u64))
			.saturating_add(T::DbWeight::get().writes(4 as u64))
	}

	fn not_unlocking_merge_schedules(l: u32, _s: u32) -> Weight {
		Weight::from_ref_time(77_405_000) // Standard Error: 7_000
			.saturating_add(Weight::from_ref_time(161_000).saturating_mul(l as u64))
			.saturating_add(T::DbWeight::get().reads(3 as u64))
			.saturating_add(T::DbWeight::get().writes(3 as u64))
	}

	fn unlocking_merge_schedules(l: u32, s: u32) -> Weight {
		Weight::from_ref_time(60_370_000) // Standard Error: 8_000
			.saturating_add(Weight::from_ref_time(247_000).saturating_mul(l as u64)) // Standard Error: 912_000
			.saturating_add(Weight::from_ref_time(4_161_000).saturating_mul(s as u64))
			.saturating_add(T::DbWeight::get().reads(3 as u64))
			.saturating_add(T::DbWeight::get().writes(3 as u64))
	}
}
